### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by ustoopia** [IRLToolkit/nginx-rtmp-auth#2]
Hi. I know this repo is a couple of years old. But I still wanted to try if it works, since it would be an ideal solution for me. Unfortunately, I get the following error message when I run the script. I did successfully install the requirements before.

```
Traceback (most recent call last):
  File "/opt/nginx-rtmp-auth/rtmpauth.py", line 11, in <module>
    hostPort = config.getint('main', 'bind_to_port')
  File "/usr/lib/python3.10/configparser.py", line 820, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 810, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 805, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: '88 # Port to bind to'
```

I'm using Python 3.10.12 on Ubuntu 22.04

**Comment by Xathz** [comment]
Maybe a config file issue. Check the port number is an integer not a string.

**Comment by ustoopia** [comment]
> Maybe a config file issue. Check the port number is an integer not a string.

How do I check that?
I haven't touched the config file. It says port 88.

**Comment by tt2468** [comment]
Try removing the comments from the INI file (as done here https://github.com/IRLToolkit/nginx-rtmp-auth/commit/94ea678c78d2673ef7e1a89525571837384bd4cc)

Configparser can't parse ini comments, so it was causing it to break.

**Comment by ustoopia** [comment]
> Try removing the comments from the INI file (as done here [94ea678](https://github.com/IRLToolkit/nginx-rtmp-auth/commit/94ea678c78d2673ef7e1a89525571837384bd4cc))
> 
> Configparser can't parse ini comments, so it was causing it to break.

Right! That indeed did the trick. I somehow feel that I should have known this, if I had even a bit of knowledge on coding. But since I don't, I just want to thank you very much for explaining it to me. 
Regards
